services:
  backend-app:
    image: elsermanuel/springboot-sqlserver:1.0
    container_name: elser_manuel_app
    ports:
      - "8080:8080"
    networks:
      - red_proyectos
    environment:
      - TZ=America/Lima
      # Configuramos la conexión usando el nombre del servicio DB
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver:1433;databaseName=ConstruccionDB;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=AdminSQL2024
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_SHOW_SQL=true
    restart: unless-stopped

networks:
  red_proyectos:
    external: true